services:
  postgres:
    container_name: fastfeet-pg
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fastfeet
      PGDATA: /data/postgres
    volumes:
      - fastfeet-pg-data:/data/postgres

volumes:
  fastfeet-pg-data: